### ISSUE TITLE
Order Fees - Service fees do not calculate as expected when per order fee applied

### ISSUE THREAD

**Issue by harrisonlemon** [big-neon/bigneon#131]
Rel #64 

**Observed behavior:**
Service fees do not calculate as expected when per order fee applied in conjunction with credit card processing fee.

Base: $10
Rev Share: $.50
Per Order Fee: $1
3% credit card processing fee

Order total should be: $11.85
Order total was: $10.82

Screengrab: https://cl.ly/5c5392ecb98f

**Comment by philipr-za** [comment]
This issue is caused by changing the Per Order fee AFTER the event was created. The event must of been created before the fee was set. An event's Per Order fee is populated when that event is created by checking the current values set for the organization. This was done so that once an event is created its Per Order fees as set as a snapshot of the org's fee setting at that time and will not affected by any Org level fee changes so that all users who buy tickets for that event will pay the same fees.

To confirm this is the issue you can set the fees as desired -> create a brand new event and then check that the fee calculation is correct.

Here is a video of a $10 ticket being added to cart on my local machine with the same fee settings as stated above:
https://cl.ly/df202826eeeb

@harrisonlemon 
@zmelamed

**Comment by Krakaw** [comment]
@harrisonlemon @zmelamed this looks like it is resolved, please re-open if that isn't the case.

**Comment by harrisonlemon** [comment]
@philipr-za @zmelamed The org-level fee should apply to all active events in an org. We will have instances when an org-level fee schedule is updated after events are onsale; the fee schedule changes should apply to all events in the org unless manually overridden by an event-level fee schedule (coming soon).

Use case: we need to update the credit card processing rate.

https://cl.ly/53179bfd78d3

**Comment by Timo614** [comment]
Just a note: the credit card fees are currently updated when changed so in the associated PR just changing the behavior of event fees such as the bigneon and client fees to behave in a similar way.

An existing cart won't have its fees changed (they will expire after a short bit but we do that so that the price doesn't change between when the order is drafted and payment unless the fees are updated due to a change to the cart (new items, etc)).

https://github.com/big-neon/bn-api/blob/master/db/src/models/orders.rs#L1521

**Comment by Timo614** [comment]
Just got off the meeting just some notes here for the future:
1. We'll be doing this same behavior for the fee schedules / ticket fees
2. We should still have the behavior override with the existing fees for now so we can manually remove the overrides one by one to avoid any shock / make sure an existing event still has the correct fees clients expect

Will make those adjustments today as well.

**Comment by Timo614** [comment]
I've added some screenshots to https://github.com/big-neon/bn-api/pull/1418

I left a note in the chatroom but for the first item we actually already do that. We don't cache the fee schedule for the old events so updating the fee schedule and creating a new cart / modifying the tickets triggering an update causes it to reflect the new values.

I've updated the logic in the PR to an override approach where individual events can have their fees set on them which overrides the organization's fees. There's no API support for doing that now but we can add it later as needed (should be rather quick as we just need to surface those fields in the API for updating an event) but for now in the DB a value can be used to override the organization company and client fees. We did that as mentioned above so we could keep the existing fees in place and remove the overrides on an event by event basis to remove any chance of surprising clients as we migrate over to this approach of mostly using the organization's current fees.

**Comment by Anziskavds** [comment]
Tested successful on develop.

I tested on the 4000 Tix event:
Base: $10
Rev Share: $3
Per Order Fee: $1
1% credit card processing fee
($10+$3+$1+1%=$14.14)

Calculated to $14.14 which is correct

**Comment by Anziskavds** [comment]
Tested successful on Beta on web and mobile web.

Event tested: Red Hot Chili Peppers
Base: $10
Rev Share: $2
Per Order Fee: $0
2.75% credit card processing fee

Order total should be: $12.33 
This is the correct amount which appear.

**Comment by Anziskavds** [comment]
Tested successful on Prod on web and mobile web
